name: AKE Daily Publish

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r orchestrator/requirements.txt
      - name: Generate content
        run: |
          python orchestrator/main.py --once
          python orchestrator/build_site.py
      - name: Commit changes
        run: |
          git config user.name "ake-bot"
          git config user.email "ake-bot@users.noreply.github.com"
          git add -A
          git diff --quiet && echo "No changes" || git commit -m "Daily publish"
      - name: Push
        run: git push
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build-and-publish
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
